"""Builtin tool provider group."""
TOOL_SPECS = [
    ('memory', 'remember'),
    ('memory', 'search_memory'),
    ('memory', 'remember_semantic'),
    ('memory', 'search_semantic_memory'),
    ('memory', 'read_observation'),
    ('user_profile', 'set_profile_image'),
    ('user_profile', 'profile_image_info'),
    ('user_profile', 'set_user_identity'),
    ('user_profile', 'set_research_preference'),
    ('repo_map', 'get_repo_map'),
    ('repo_map', 'search_repo_symbols'),
    ('repo_map', 'read_repo_symbol'),
    ('repo_diagnostics', 'repo_status'),
    ('repo_diagnostics', 'repo_diff'),
    ('repo_diagnostics', 'repo_checks'),
    ('repo_diagnostics', 'dependency_audit'),
    ('repo_diagnostics', 'tool_health'),
    ('primitives', 'current_time'),
    ('primitives', 'hostname'),
    ('primitives', 'environment_summary'),
    ('pipeline', 'run_pipeline'),
    ('pipeline', 'run_recipe'),
    ('pipeline', 'list_recipes'),
    ('pipeline', 'search_recipes'),
    ('pipeline', 'save_recipe'),
    ('recipe_compat', 'recipe_coverage'),
    ('workspace', 'read_file'),
    ('workspace', 'write_file'),
    ('system', 'execute_shell'),
    ('system', 'execute_python'),
]
