"""Builtin tool provider group."""
TOOL_SPECS = [
    ('observation_tools', 'diff_observations'),
    ('host_tools', 'host_snapshot'),
    ('host_tools', 'gpu_snapshot_dict'),
    ('host_tools', 'ollama_runtime_snapshot'),
    ('host_tools', 'network_snapshot'),
    ('host_tools', 'network_reachability'),
    ('host_tools', 'list_host_monitor_events'),
    ('host_tools', 'read_host_file'),
    ('host_tools', 'read_host_journal'),
    ('host_tools', 'tail_host_log'),
    ('host_diagnostics', 'process_snapshot'),
    ('host_diagnostics', 'pressure_snapshot'),
    ('host_diagnostics', 'filesystem_snapshot'),
    ('host_diagnostics', 'service_health'),
    ('network_diagnostics', 'neighbor_snapshot'),
    ('network_diagnostics', 'connection_snapshot'),
    ('network_diagnostics', 'dns_diagnose'),
    ('network_diagnostics', 'network_path'),
    ('network_diagnostics', 'endpoint_probe'),
    ('network_diagnostics', 'http_probe'),
    ('network_mapper', 'local_subnets'),
    ('network_mapper', 'scan_subnet'),
    ('network_mapper', 'map_network'),
    ('mdns_scanner', 'scan_mdns'),
]
